services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: doc_intel
      POSTGRES_USER: doc_user
      POSTGRES_PASSWORD: doc_pass
    ports:
      - "${POSTGRES_PORT:-3001}:5432"
    volumes:
      - ${POSTGRES_VOLUME:-postgres_data}:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    restart: always
    ports:
      - "${CHROMADB_PORT:-3002}:8000"
    volumes:
      - ${CHROMA_VOLUME:-chroma_data}:/chroma/.chroma

  llamacpp-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llamacpp-server
    profiles:
      - llama
    ports:
      - "${LLAMA_CPP_PORT:-3005}:8080"
    volumes:
      - ${LLAMA_CPP_VOLUME:-llama_cpp_data}:/models
    environment:
      # alternatively, you can use "LLAMA_ARG_MODEL_URL" to download the model
      LLAMA_ARG_CTX_SIZE: 4096
      LLAMA_ARG_N_PARALLEL: 2
      LLAMA_ARG_ENDPOINT_METRICS: 1
      LLAMA_ARG_PORT: 8080

volumes:
  postgres_data:
  chroma_data:
  llama_cpp_data:
